 #
 #	========================================================
 #
 #	C++Kit
 # 	Copyright WestCo, all rights reserved.
 #
 # 	========================================================
 #

.PHONY: mcc-build
mcc-build:
	dmd -I../ $(wildcard *.d) -ofmpcc