 #
 #	========================================================
 #
 #	MPCC
 # 	Copyright 2024, Mahrouss Logic, all rights reserved.
 #
 # 	========================================================
 #
 
.PHONY: all
all:
	mvn clean javafx:run