 #
 #	========================================================
 #
 #	MP-UX C Compiler
 # 	Copyright 2024, Mahrouss Logic, all rights reserved.
 #
 # 	========================================================
 #

# build mpcc
.PHONY: mpcc-build
mpcc-build:
	dmd -I../ $(wildcard *.d) -ofmpcc