 #
 #	========================================================
 #
 #	MP-UX Tools
 # 	Copyright 2024, Mahrouss Logic, all rights reserved.
 #
 # 	========================================================
 #

# build mpcc
.PHONY: build-installer
build-installer:
	dmd -I../ install.d -ofinstall.out