 #
 #	========================================================
 #
 #	MultiProcessor Tools
 # 	Copyright Mahrouss Logic, all rights reserved.
 #
 # 	========================================================
 #

# build mpcc
.PHONY: build-installer
build-installer:
	dmd -I../ install.d -ofinstall.out