name: C/C++ CI (CompilerKit)

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Packages
      run: sudo apt update && sudo apt install build-essential && git clone https://github.com/nekernel-org/necti && cd necti && make build-nebuild && cd .. && cd dev/CompilerKit && nebuild ck-posix.json


