name: Nectar Kits OS X (Nectar, Develop)

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Attempt NeBuild
      run: sudo curl https://github.com/ne-foss/ne-build/releases/download/v0.0.6-apple-m1/nebuild-osx -o sanity-test
    - name: Build CompilerKit and DebuggerKit
      run: sudo curl https://github.com/ne-foss/ne-build/releases/download/v0.0.6-apple-m1/nebuild-osx -o /bin/nebuild && sudo chmod +x /bin/nebuild && sudo apt update && sudo apt install build-essential && sudo apt install libboost-dev &&
          cd src/CompilerKit && nebuild ck-osx.json &&
          cd ../DebuggerKit && nebuild dk-osx.json

